Repository anmedio/junost, pull requests merged in 2020-01, with the labels that each got.

#24 fix jest description
  src/react/grades.js
Labels: good first issue, pr: syntax error fix ✏️, priority: medium

#18 Add emmet, weinre, linux from scratch
  src/react/grades.js
Labels: good first issue, pr: enhancement add 💅, priority: medium, status: confirmed, type: enhancement 💅

#25 add grade Makefile
  Makefile
  docs/static/js/bundle.js
  src/react/grades.js
Labels: good first issue, grade: nodejs, pr: new feature add 🚀, priority: medium

#26 Add CSS-in-JS to Frontend Junior grade
  src/react/grades.js
Labels: good first issue, grade: frontend, pr: enhancement add 💅, priority: low

#21 feat: Add .idea directory to gitignore
  .gitignore
Labels: pr: enhancement add 💅, priority: low

#23 First version of mandatory skills for Java grades.
  src/react/grades.js
Labels: good first issue, grade: java, pr: enhancement add 💅, priority: high

#22 Refactor grades.js
  docs/static/js/bundle.js
  src/react/grades.js
Labels: good first issue, pr: refactoring 💫, priority: high, status: confirmed, type: refactoring 💫
